language: php
php:
  - '5.6'
  - '7.0'
before_script:
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml tests

after_script:
  - php vendor/bin/coveralls -v
